version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: employee_service
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5430:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    image: employee_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5430/employee_service
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
    depends_on:
      - db
    ports:
      - "8081:8081"

volumes:
  db-data:
